name: preMETIS
channels:
  - conda-forge  
  - defaults  
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pip
  - python=3.12
  - scipy
  - suitesparse  
  - scikit-sparse  
  - seaborn
  - pip:
      - networkx
      - pymetis
      - ipykernel
